# Generated by Django 2.2.8 on 2020-03-25 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0108_v370_unifiedjob_dependencies_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, help_text='Job task status', max_length=256)),
                ('config', models.CharField(max_length=256)),
                ('domain', models.CharField(max_length=256)),
                ('prev_step_id', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
