# Generated by Django 2.2.8 on 2020-03-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_deployhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployhistory',
            name='prev_step_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
