# Generated by Django 2.2.8 on 2020-03-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_auto_20200325_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
