# Generated by Django 2.2.8 on 2020-03-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_auto_20200325_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployhistory',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
