# Generated by Django 2.2.8 on 2020-03-25 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_auto_20200325_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
