# Generated by Django 2.2.8 on 2020-03-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_auto_20200325_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystream',
            name='deploy_history',
            field=models.ManyToManyField(blank=True, to='main.DeployHistory'),
        ),
    ]
