# Generated by Django 2.2.8 on 2020-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_activitystream_deploy_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
