# Generated by Django 2.2.8 on 2020-03-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_remove_deployhistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployhistory',
            name='user',
        ),
    ]
