# Generated by Django 2.2.8 on 2020-04-01 12:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('main', '0120_remove_deployhistory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('config', models.CharField(max_length=256)),
                ('deployHistoryIds', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('created_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'deploytemplate', 'model_name': 'deploytemplate', 'app_label': 'main'}(class)s_created+", to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'deploytemplate', 'model_name': 'deploytemplate', 'app_label': 'main'}(class)s_modified+", to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
