# Generated by Django 2.2.8 on 2020-04-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_deploytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystream',
            name='deploy_template',
            field=models.ManyToManyField(blank=True, to='main.DeployTemplate'),
        ),
    ]
