# Generated by Django 2.2.8 on 2020-04-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_activitystream_deploy_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploytemplate',
            name='config',
        ),
        migrations.AlterField(
            model_name='deployhistory',
            name='config',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
