# Generated by Django 2.2.8 on 2020-04-09 09:01

import awx.main.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_auto_20200407_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytemplate',
            name='admin_role',
            field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role='singleton:system_administrator', related_name='+', to='main.Role'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='deploytemplate',
            name='member_role',
            field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=['admin_role'], related_name='+', to='main.Role'),
            preserve_default='True',
        ),
    ]
