# Generated by Django 2.2.8 on 2020-04-17 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_auto_20200415_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='job_template',
            new_name='job_templates',
        ),
    ]
