# Generated by Django 2.2.8 on 2020-06-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0128_deployhistory_setuper'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployhistory',
            name='picker',
            field=models.BooleanField(default=None),
        ),
    ]
