# Generated by Django 2.2.8 on 2020-06-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0130_auto_20200616_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployhistory',
            name='job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployhistorys', to='main.Job'),
        ),
    ]
