# Generated by Django 2.2.8 on 2020-06-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_auto_20200616_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployhistory',
            name='on_failed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployhistory',
            name='on_success',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
