# Generated by Django 2.2.8 on 2020-06-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_auto_20200619_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploytemplate',
            name='deployHistoryIds',
        ),
        migrations.AddField(
            model_name='deploytemplate',
            name='tree',
            field=models.TextField(blank=True, default=None),
        ),
    ]
