# Generated by Django 2.2.8 on 2020-07-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0133_auto_20200630_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployhistory',
            name='action',
        ),
        migrations.RemoveField(
            model_name='deployhistory',
            name='config',
        ),
        migrations.RemoveField(
            model_name='deployhistory',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='deployhistory',
            name='job',
        ),
        migrations.RemoveField(
            model_name='deployhistory',
            name='on_failed',
        ),
        migrations.RemoveField(
            model_name='deployhistory',
            name='on_success',
        ),
        migrations.RemoveField(
            model_name='deployhistory',
            name='picker',
        ),
        migrations.RemoveField(
            model_name='deployhistory',
            name='prev_step_id',
        ),
        migrations.RemoveField(
            model_name='deployhistory',
            name='setuper',
        ),
        migrations.RemoveField(
            model_name='deployhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='deployhistory',
            name='tree',
            field=models.TextField(blank=True, default=None),
        ),
    ]
